// <auto-generated />

using HospitalClassLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hospital_Class_Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211106161219_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hospital_Class_Library.Graphical_Editor.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The administrative center of Oasis Healthcare",
                            Name = "Oasis Main Building"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The treatment facility of Oasis Healthcare",
                            Name = "Oasis Treatment Center"
                        });
                });

            modelBuilder.Entity("Hospital_Class_Library.Graphical_Editor.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("FreeBeds")
                        .HasColumnType("integer");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 246.0,
                            Name = "0A",
                            Status = 1,
                            Type = 4,
                            Width = 255.0,
                            X = 9.0,
                            Y = 9.0
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 243.0,
                            Name = "0B",
                            Status = 1,
                            Type = 4,
                            Width = 256.0,
                            X = 9.0,
                            Y = 563.0
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 284.0,
                            Name = "0C",
                            Status = 1,
                            Type = 4,
                            Width = 234.0,
                            X = 265.0,
                            Y = 466.0
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 1,
                            Height = 190.0,
                            Name = "0A",
                            Status = 1,
                            Type = 0,
                            Width = 235.0,
                            X = 264.0,
                            Y = 65.0
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 1,
                            Height = 190.0,
                            Name = "0B",
                            Status = 1,
                            Type = 0,
                            Width = 235.0,
                            X = 859.0,
                            Y = 65.0
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 1,
                            Height = 190.0,
                            Name = "0A",
                            Status = 1,
                            Type = 1,
                            Width = 360.0,
                            X = 499.0,
                            Y = 65.0
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 1,
                            Height = 172.37,
                            Name = "0A",
                            Status = 1,
                            Type = 3,
                            Width = 226.0,
                            X = 868.0,
                            Y = 577.63
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 1,
                            Height = 172.37,
                            Name = "0B",
                            Status = 1,
                            Type = 3,
                            Width = 226.0,
                            X = 868.0,
                            Y = 405.0
                        },
                        new
                        {
                            Id = 9,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 154.0,
                            Name = "Men Restroom",
                            Status = 1,
                            Type = 5,
                            Width = 119.0,
                            X = 9.0,
                            Y = 255.0
                        },
                        new
                        {
                            Id = 10,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 154.0,
                            Name = "Women Restroom",
                            Status = 1,
                            Type = 5,
                            Width = 119.0,
                            X = 9.0,
                            Y = 409.0
                        },
                        new
                        {
                            Id = 11,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 77.0,
                            Name = "L",
                            Status = 1,
                            Type = 6,
                            Width = 77.0,
                            X = 187.0,
                            Y = 255.0
                        },
                        new
                        {
                            Id = 12,
                            BuildingId = 1,
                            Floor = 0,
                            FreeBeds = 0,
                            Height = 150.0,
                            Name = "S1",
                            Status = 1,
                            Type = 7,
                            Width = 77.0,
                            X = 187.0,
                            Y = 413.0
                        },
                        new
                        {
                            Id = 13,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 246.0,
                            Name = "1A",
                            Status = 1,
                            Type = 4,
                            Width = 255.0,
                            X = 9.0,
                            Y = 9.0
                        },
                        new
                        {
                            Id = 14,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 243.0,
                            Name = "1B",
                            Status = 1,
                            Type = 4,
                            Width = 256.0,
                            X = 9.0,
                            Y = 563.0
                        },
                        new
                        {
                            Id = 15,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 284.0,
                            Name = "1C",
                            Status = 1,
                            Type = 4,
                            Width = 234.0,
                            X = 265.0,
                            Y = 466.0
                        },
                        new
                        {
                            Id = 16,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 1,
                            Height = 190.0,
                            Name = "1A",
                            Status = 1,
                            Type = 0,
                            Width = 235.0,
                            X = 264.0,
                            Y = 65.0
                        },
                        new
                        {
                            Id = 17,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 1,
                            Height = 190.0,
                            Name = "1B",
                            Status = 1,
                            Type = 0,
                            Width = 235.0,
                            X = 859.0,
                            Y = 65.0
                        },
                        new
                        {
                            Id = 18,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 1,
                            Height = 190.0,
                            Name = "1A",
                            Status = 1,
                            Type = 1,
                            Width = 360.0,
                            X = 499.0,
                            Y = 65.0
                        },
                        new
                        {
                            Id = 19,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 1,
                            Height = 172.37,
                            Name = "1A",
                            Status = 1,
                            Type = 3,
                            Width = 226.0,
                            X = 868.0,
                            Y = 577.63
                        },
                        new
                        {
                            Id = 20,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 1,
                            Height = 172.37,
                            Name = "1B",
                            Status = 1,
                            Type = 3,
                            Width = 226.0,
                            X = 868.0,
                            Y = 405.0
                        },
                        new
                        {
                            Id = 21,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 154.0,
                            Name = "Men Restroom",
                            Status = 1,
                            Type = 5,
                            Width = 119.0,
                            X = 9.0,
                            Y = 255.0
                        },
                        new
                        {
                            Id = 22,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 154.0,
                            Name = "Women Restroom",
                            Status = 1,
                            Type = 5,
                            Width = 119.0,
                            X = 9.0,
                            Y = 409.0
                        },
                        new
                        {
                            Id = 23,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 77.0,
                            Name = "L",
                            Status = 1,
                            Type = 6,
                            Width = 77.0,
                            X = 187.0,
                            Y = 255.0
                        },
                        new
                        {
                            Id = 24,
                            BuildingId = 1,
                            Floor = 1,
                            FreeBeds = 0,
                            Height = 150.0,
                            Name = "S1",
                            Status = 1,
                            Type = 7,
                            Width = 77.0,
                            X = 187.0,
                            Y = 413.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
