name: Hospital Build and Test

on:
  pull_request:
    branches: [ master, develop ]
      
env:
  DOTNET_VERSION: '3.1.x'
  PROJECT_PATH: './Hospital'
    
jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:3.1
    strategy:
      matrix: 
        test_project: ['HospitalIntegrationTests', 'HospitalUnitTests']
    
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
        
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore ${{ env.PROJECT_PATH }}

    - name: Test
      run: dotnet test --no-restore --verbosity normal ${{ env.PROJECT_PATH }}/${{ matrix.test_project }} /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger "trx;LogFileName=${{ matrix.test_project }}.trx" --results-directory "./TestResults-${{ matrix.test_project }}"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-results-${{ matrix.test_project }}
        path: TestResults-${{ matrix.test_project }}
      if: ${{ always() }}

    - name: Upload Opencover results
      uses: actions/upload-artifact@v2
      with:
        name: opencover-results-${{ matrix.test_project }}
        path: ${{ matrix.test_project }}/coverage.opencover.xml
      if: ${{ always() }} 

