name: Deploy to server
on:
  workflow_dispatch:
  push:
    branches:  [master]
jobs:

  Deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    steps:
    - name: deploy-on-server
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 200m
        host: 79.101.34.218
        username: student
        key: ${{ secrets.SSH_KEY }}
        port: 22215
        script: |
          cd DevOps
          git pull
          git checkout bugfix/frontend
          cd docker-compose
          docker-compose build
          docker-compose up -d
