name: Deploy to server
on:
  workflow_dispatch:
  push:
    branches:  [master]
jobs:

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: anagavrilovic
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Hospital
          push: true
          tags: anagavrilovic/hospital:latest

  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: build-and-publish-docker-image
    steps:
    - name: deploy-on-server
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 200m
        host: 79.101.34.218
        username: student
        key: ${{ secrets.SSH_KEY }}
        port: 22215
        script: |
          cd DevOps
          git pull
          git checkout bugfix/frontend
          cd docker-compose
          docker-compose build --no-cache
          docker-compose pull
          docker-compose up -d
